[tool.poetry]
name = "shared-logging"
version = "0.1.0"
description = "Centralized structured logging for the Telecom CCAI project."
authors = ["Platform Team <platform@example.com>"]
readme = "README.md"
packages = [{include = "shared_logging"}]

[tool.poetry.dependencies]
python = "^3.11"
python-json-logger = "^2.0.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
